version: "3"

services:
  database:
    image: mysql
    container_name: database_mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_HOST=localhost
    volumes:
      - mysqldata:/data/mysql

volumes:
  mysqldata:
    driver: local
